name: Deploy New Nginx Instance

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Terraform Configuration
      working-directory: ./scripts
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: python container_name_generator.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"

    - name: Terraform Init
      working-directory: ./terraform
      env:
        client_id: ${{ secrets.AZ_CLIENT_ID }}
        client_secret: ${{ secrets.AZCLIENT_SECRET }}
        subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.AZ_TENANT_ID }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      env:
        client_id: ${{ secrets.AZ_CLIENT_ID }}
        client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
        subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.AZ_TENANT_ID }}
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
      run: terraform apply -auto-approve
