name: Deploy New Nginx Instance

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Terraform Configuration
      working-directory: ./scripts
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: python container_name_generator.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"

    - name: Terraform Init
      working-directory: ./terraform
      env:
        TF_VAR_AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
        TF_VAR_AZURE_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        TF_VAR_AZURE_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        TF_VAR_AZURE_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      env:
        TF_VAR_AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
        TF_VAR_AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        TF_VAR_AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        TF_VAR_AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
        TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: terraform apply -auto-approve
