name: Deploy New Nginx Instance

on:
  workflow_dispatch:  # Manual trigger

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Terraform Configuration
      working-directory: ./scripts
      run: python container_name_generator.py

    # Debugging step to print environment variables
    - name: Debug Environment Variables
      run: |
        echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
        echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
        echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
        echo "ARM_TENANT_ID: $ARM_TENANT_ID"
        # echo "DOCKER_USERNAME: $DOCKER_USERNAME"
        # echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.3.0"

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve